### ISSUE TITLE
Python assertion error when writing output to layer

### ISSUE THREAD

**Issue by srivatsa-s24** [REDcatch/Volume_calculation_for_QGIS3#1]
When I try to compute volume, it exits with following error -
```
Traceback (most recent call last):
  File "/home/srivatsa/.local/share/QGIS/QGIS3/profiles/default/python/plugins/volume_calculation_tool/volume_calculation_tool.py", line 366, in calculationFinished
    self.writeResultsToLayer()
  File "/home/srivatsa/.local/share/QGIS/QGIS3/profiles/default/python/plugins/volume_calculation_tool/volume_calculation_tool.py", line 451, in writeResultsToLayer
    with edit(self.current_task_options.vector_layer):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/edit.py", line 38, in __enter__
    assert self.layer.startEditing()
AssertionError
```

Following are the system details:

Python version: 3.6.9 [GCC 8.4.0] 
QGIS version: 3.16.0 Hannover
Operating System: Ubuntu 18.04

**Comment by REDcatch** [comment]
Hi, can you please send us the dataset? DGM and Polygon layer would be perfect.

support @ redcatch.at

Can you please check:
- are both layers in the same coordinate system?

cheers

**Comment by srivatsa-s24** [comment]
Sorry, issue was from my end. I had turned on `Editing` feature on the vector layer, which caused the above issue.
