### ISSUE TITLE
Error handling improvements

### ISSUE THREAD

**Issue by AlisterH** [REDcatch/Volume_calculation_for_QGIS3#9]
Trying to debug the crashes in the other ticket, I've noticed some situations where it doesn't crash QGIS, but the error handling could be improved:
- if I create a vector layer where none of the features actually overlap with the DEM, it fails silently (it just doesn't appear to do anything).
- if I try to run it with no vector layers in the project, it displays an error message which says it is closing the plugin, but then crashes when I click OK.  Fortunately QGIS itself isn't crashed, but since you're already detecting the problem I imagine it shouldn't be too hard to avoid this crash (I note that when it detects the layer CRSs don't match it closes the plugin without an error).
- if I create some polygons in a new memory layer and try to use it without saving the layer, it fails _almost_ silently (the plugin just doesn't appear to do anything, but there is a notification in the main QGIS window about a python error).

The errors are:
````
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 466, in workflow
    self.gatherInputInfo()
  File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 511, in gatherInputInfo
    vector_layer = QgsProject.instance().mapLayersByName(self.dlg.mFieldComboPolygon.currentText())[0]
IndexError: list index out of range
````
And 
````
2022-09-08T13:09:16     WARNING    Traceback (most recent call last):
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 474, in workflow
              self.doSimpleWorkflow()
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 477, in doSimpleWorkflow
              self.getVolumeSimple()
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 625, in getVolumeSimple
              internal_external_map[feature.id()].append(feature.attributes()[index])
             IndexError: list index out of range
````

**Comment by AlisterH** [comment]
Actually, one of those errors might have been in yet another situation, because this is what I get now in the third situation:
````
2022-09-08T13:24:01     WARNING    Traceback (most recent call last):
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 366, in calculationFinished
              self.writeResultsToLayer()
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 452, in writeResultsToLayer
              with edit(self.current_task_options.vector_layer):
              File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\core\additions\edit.py", line 38, in __enter__
              assert self.layer.startEditing()
             AssertionError
`````

**Comment by AlisterH** [comment]
At some point I also saw this error, but I lost track of the situation that it occurred in:
````
 2022-09-08T12:46:58     WARNING    Traceback (most recent call last):
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 474, in workflow
              self.doSimpleWorkflow()
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 477, in doSimpleWorkflow
              self.getVolumeSimple()
              File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\volume_calculation_tool\volume_calculation_tool.py", line 629, in getVolumeSimple
              absolute_avg_height = abs(internal_external_map[key][1] - internal_external_map[key][2])
             TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
````

**Comment by distbug** [comment]
Yeah, agreed error handling/feedback should be improved. At the moment the plugin expects the user to not do anything it is not designed to do. There are also checks missing.
